//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementPins
    {
        public int PinId { get; set; }
        public int AnnouncementId { get; set; }
        public int UserId { get; set; }
        public System.DateTime PinnedAt { get; set; }
    
        public virtual Announcements Announcements { get; set; }
        public virtual Users Users { get; set; }
    }
}
