//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcements
    {
        public Announcements()
        {
            this.AnnouncementAttachments = new HashSet<AnnouncementAttachments>();
            this.AnnouncementPins = new HashSet<AnnouncementPins>();
            this.AnnouncementReads = new HashSet<AnnouncementReads>();
        }
    
        public int AnnouncementId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Priority { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public bool IsPinned { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
        public string TargetAudience { get; set; }
        public Nullable<int> TargetGroupId { get; set; }
        public Nullable<int> TargetUserId { get; set; }
    
        public virtual ICollection<AnnouncementAttachments> AnnouncementAttachments { get; set; }
        public virtual ICollection<AnnouncementPins> AnnouncementPins { get; set; }
        public virtual ICollection<AnnouncementReads> AnnouncementReads { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Groups Groups1 { get; set; }
        public virtual Users Users3 { get; set; }
    }
}
