//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementAttachments
    {
        public int AttachmentId { get; set; }
        public int AnnouncementId { get; set; }
        public string FileName { get; set; }
        public long FileSize { get; set; }
        public string ContentType { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<int> UploadedById { get; set; }
        public System.DateTime UploadedAt { get; set; }
    
        public virtual Announcements Announcements { get; set; }
        public virtual Users Users { get; set; }
    }
}
