//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuratorProfiles
    {
        public int CuratorProfileId { get; set; }
        public int UserId { get; set; }
        public string Education { get; set; }
        public string EducationInstitution { get; set; }
        public string Specialty { get; set; }
        public Nullable<int> TeachingExperienceYears { get; set; }
        public Nullable<int> TotalExperienceYears { get; set; }
        public string AcademicDegree { get; set; }
        public string AcademicTitle { get; set; }
        public string QualificationCategory { get; set; }
        public Nullable<System.DateTime> LastQualificationDate { get; set; }
        public string QualificationInstitution { get; set; }
        public string ScientificAchievements { get; set; }
        public string Publications { get; set; }
        public string Awards { get; set; }
        public string AdditionalCourses { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
