//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DocumentId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> UploadedById { get; set; }
        public string Title { get; set; }
        public string DocumentType { get; set; }
        public string FilePath { get; set; }
        public string FileSize { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
