//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dormitories
    {
        public Dormitories()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int DormitoryId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string CommandantName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> TotalRooms { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}
