//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventProtocols
    {
        public int ProtocolId { get; set; }
        public int EventId { get; set; }
        public string Agenda { get; set; }
        public string Decisions { get; set; }
        public string Attendees { get; set; }
        public string AbsentStudents { get; set; }
        public string Secretary { get; set; }
        public Nullable<System.DateTime> SignedAt { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Events Events { get; set; }
    }
}
