//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.EventProtocols = new HashSet<EventProtocols>();
        }
    
        public int EventId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string Title { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public string Location { get; set; }
        public string EventType { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual ICollection<EventProtocols> EventProtocols { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
