//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeHistory
    {
        public int HistoryId { get; set; }
        public int GradeId { get; set; }
        public Nullable<int> ChangedById { get; set; }
        public byte OldValue { get; set; }
        public byte NewValue { get; set; }
        public string ChangeReason { get; set; }
        public System.DateTime ChangedAt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Grades Grades { get; set; }
    }
}
