//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Announcements = new HashSet<Announcements>();
            this.Announcements1 = new HashSet<Announcements>();
            this.Assignments = new HashSet<Assignments>();
            this.Documents = new HashSet<Documents>();
            this.Events = new HashSet<Events>();
            this.LessonNotes = new HashSet<LessonNotes>();
            this.Schedule = new HashSet<Schedule>();
            this.Students = new HashSet<Students>();
            this.Subjects = new HashSet<Subjects>();
        }
    
        public int GroupId { get; set; }
        public int YearId { get; set; }
        public Nullable<int> CuratorId { get; set; }
        public string GroupName { get; set; }
        public string Specialty { get; set; }
        public string SpecialtyCode { get; set; }
        public byte Course { get; set; }
        public byte Semester { get; set; }
        public string EducationForm { get; set; }
        public string EducationBasis { get; set; }
        public int StudentCount { get; set; }
        public bool IsGraduated { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual AcademicYears AcademicYears { get; set; }
        public virtual ICollection<Announcements> Announcements { get; set; }
        public virtual ICollection<Announcements> Announcements1 { get; set; }
        public virtual ICollection<Assignments> Assignments { get; set; }
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ICollection<Events> Events { get; set; }
        public virtual ICollection<LessonNotes> LessonNotes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<Students> Students { get; set; }
        public virtual ICollection<Subjects> Subjects { get; set; }
    }
}
