//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonNotes
    {
        public int NoteId { get; set; }
        public int GroupId { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime LessonDate { get; set; }
        public string NoteText { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
