//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CollegeJournalEntities : DbContext
    {
        public CollegeJournalEntities()
            : base("name=CollegeJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicYears> AcademicYears { get; set; }
        public DbSet<Achievements> Achievements { get; set; }
        public DbSet<AnnouncementAttachments> AnnouncementAttachments { get; set; }
        public DbSet<AnnouncementPins> AnnouncementPins { get; set; }
        public DbSet<AnnouncementReads> AnnouncementReads { get; set; }
        public DbSet<Announcements> Announcements { get; set; }
        public DbSet<Assignments> Assignments { get; set; }
        public DbSet<Attendance> Attendance { get; set; }
        public DbSet<AuditLog> AuditLog { get; set; }
        public DbSet<CuratorProfiles> CuratorProfiles { get; set; }
        public DbSet<Documents> Documents { get; set; }
        public DbSet<Dormitories> Dormitories { get; set; }
        public DbSet<EventProtocols> EventProtocols { get; set; }
        public DbSet<Events> Events { get; set; }
        public DbSet<GradeHistory> GradeHistory { get; set; }
        public DbSet<Grades> Grades { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<LessonNotes> LessonNotes { get; set; }
        public DbSet<MonthlyGrades> MonthlyGrades { get; set; }
        public DbSet<Parents> Parents { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<StudentSocialInfo> StudentSocialInfo { get; set; }
        public DbSet<Subjects> Subjects { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<vw_AttendanceSummary> vw_AttendanceSummary { get; set; }
        public DbSet<vw_AuditLog> vw_AuditLog { get; set; }
        public DbSet<vw_DeletedRecords> vw_DeletedRecords { get; set; }
        public DbSet<vw_GradeAverage> vw_GradeAverage { get; set; }
        public DbSet<vw_SocialStudents> vw_SocialStudents { get; set; }
        public DbSet<vw_StudentCard> vw_StudentCard { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_AddAcademicYear(string title, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> isCurrent, Nullable<int> adminId)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var isCurrentParameter = isCurrent.HasValue ?
                new ObjectParameter("IsCurrent", isCurrent) :
                new ObjectParameter("IsCurrent", typeof(bool));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AddAcademicYear", titleParameter, startDateParameter, endDateParameter, isCurrentParameter, adminIdParameter);
        }
    
        public virtual int sp_AddAttachment(Nullable<int> announcementId, string fileName, Nullable<long> fileSize, string contentType, byte[] fileData, Nullable<int> uploadedById)
        {
            var announcementIdParameter = announcementId.HasValue ?
                new ObjectParameter("AnnouncementId", announcementId) :
                new ObjectParameter("AnnouncementId", typeof(int));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var fileSizeParameter = fileSize.HasValue ?
                new ObjectParameter("FileSize", fileSize) :
                new ObjectParameter("FileSize", typeof(long));
    
            var contentTypeParameter = contentType != null ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(string));
    
            var fileDataParameter = fileData != null ?
                new ObjectParameter("FileData", fileData) :
                new ObjectParameter("FileData", typeof(byte[]));
    
            var uploadedByIdParameter = uploadedById.HasValue ?
                new ObjectParameter("UploadedById", uploadedById) :
                new ObjectParameter("UploadedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddAttachment", announcementIdParameter, fileNameParameter, fileSizeParameter, contentTypeParameter, fileDataParameter, uploadedByIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AddDormitory(string name, string address, string commandantName, string phone, Nullable<int> totalRooms, Nullable<int> adminId)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var commandantNameParameter = commandantName != null ?
                new ObjectParameter("CommandantName", commandantName) :
                new ObjectParameter("CommandantName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var totalRoomsParameter = totalRooms.HasValue ?
                new ObjectParameter("TotalRooms", totalRooms) :
                new ObjectParameter("TotalRooms", typeof(int));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AddDormitory", nameParameter, addressParameter, commandantNameParameter, phoneParameter, totalRoomsParameter, adminIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AddGroup(Nullable<int> yearId, Nullable<int> curatorId, string groupName, string specialty, string specialtyCode, Nullable<byte> course, Nullable<byte> semester, string eduForm, string eduBasis, Nullable<int> adminId)
        {
            var yearIdParameter = yearId.HasValue ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(int));
    
            var curatorIdParameter = curatorId.HasValue ?
                new ObjectParameter("CuratorId", curatorId) :
                new ObjectParameter("CuratorId", typeof(int));
    
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            var specialtyParameter = specialty != null ?
                new ObjectParameter("Specialty", specialty) :
                new ObjectParameter("Specialty", typeof(string));
    
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("SpecialtyCode", specialtyCode) :
                new ObjectParameter("SpecialtyCode", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(byte));
    
            var semesterParameter = semester.HasValue ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(byte));
    
            var eduFormParameter = eduForm != null ?
                new ObjectParameter("EduForm", eduForm) :
                new ObjectParameter("EduForm", typeof(string));
    
            var eduBasisParameter = eduBasis != null ?
                new ObjectParameter("EduBasis", eduBasis) :
                new ObjectParameter("EduBasis", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AddGroup", yearIdParameter, curatorIdParameter, groupNameParameter, specialtyParameter, specialtyCodeParameter, courseParameter, semesterParameter, eduFormParameter, eduBasisParameter, adminIdParameter);
        }
    
        public virtual ObjectResult<sp_AddStudent_Result> sp_AddStudent(string login, string passwordHash, string lastName, string firstName, string middleName, string phone, string email, Nullable<int> groupId, Nullable<System.DateTime> birthDate, string gender, string studyBasis, string studentCode, Nullable<System.DateTime> enrollmentDate, Nullable<int> addedById)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var birthDateParameter = birthDate.HasValue ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var studyBasisParameter = studyBasis != null ?
                new ObjectParameter("StudyBasis", studyBasis) :
                new ObjectParameter("StudyBasis", typeof(string));
    
            var studentCodeParameter = studentCode != null ?
                new ObjectParameter("StudentCode", studentCode) :
                new ObjectParameter("StudentCode", typeof(string));
    
            var enrollmentDateParameter = enrollmentDate.HasValue ?
                new ObjectParameter("EnrollmentDate", enrollmentDate) :
                new ObjectParameter("EnrollmentDate", typeof(System.DateTime));
    
            var addedByIdParameter = addedById.HasValue ?
                new ObjectParameter("AddedById", addedById) :
                new ObjectParameter("AddedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AddStudent_Result>("sp_AddStudent", loginParameter, passwordHashParameter, lastNameParameter, firstNameParameter, middleNameParameter, phoneParameter, emailParameter, groupIdParameter, birthDateParameter, genderParameter, studyBasisParameter, studentCodeParameter, enrollmentDateParameter, addedByIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AddSubject(Nullable<int> groupId, Nullable<int> teacherId, string subjectName, Nullable<int> hoursTotal, Nullable<int> hoursLecture, Nullable<int> hoursPractice, Nullable<int> hoursLab, Nullable<int> hoursSelfStudy, string semester, string controlType, Nullable<int> adminId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var teacherIdParameter = teacherId.HasValue ?
                new ObjectParameter("TeacherId", teacherId) :
                new ObjectParameter("TeacherId", typeof(int));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var hoursTotalParameter = hoursTotal.HasValue ?
                new ObjectParameter("HoursTotal", hoursTotal) :
                new ObjectParameter("HoursTotal", typeof(int));
    
            var hoursLectureParameter = hoursLecture.HasValue ?
                new ObjectParameter("HoursLecture", hoursLecture) :
                new ObjectParameter("HoursLecture", typeof(int));
    
            var hoursPracticeParameter = hoursPractice.HasValue ?
                new ObjectParameter("HoursPractice", hoursPractice) :
                new ObjectParameter("HoursPractice", typeof(int));
    
            var hoursLabParameter = hoursLab.HasValue ?
                new ObjectParameter("HoursLab", hoursLab) :
                new ObjectParameter("HoursLab", typeof(int));
    
            var hoursSelfStudyParameter = hoursSelfStudy.HasValue ?
                new ObjectParameter("HoursSelfStudy", hoursSelfStudy) :
                new ObjectParameter("HoursSelfStudy", typeof(int));
    
            var semesterParameter = semester != null ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(string));
    
            var controlTypeParameter = controlType != null ?
                new ObjectParameter("ControlType", controlType) :
                new ObjectParameter("ControlType", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AddSubject", groupIdParameter, teacherIdParameter, subjectNameParameter, hoursTotalParameter, hoursLectureParameter, hoursPracticeParameter, hoursLabParameter, hoursSelfStudyParameter, semesterParameter, controlTypeParameter, adminIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AddTeacher(string lastName, string firstName, string middleName, Nullable<bool> isActive, string login, string passwordHash, string phone, string email, Nullable<int> adminId)
        {
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AddTeacher", lastNameParameter, firstNameParameter, middleNameParameter, isActiveParameter, loginParameter, passwordHashParameter, phoneParameter, emailParameter, adminIdParameter);
        }
    
        public virtual int sp_AddUser(string login, string passwordHash, string roleName, string lastName, string firstName, string middleName, string phone, string email, Nullable<int> adminId)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddUser", loginParameter, passwordHashParameter, roleNameParameter, lastNameParameter, firstNameParameter, middleNameParameter, phoneParameter, emailParameter, adminIdParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_AssignCurator(Nullable<int> groupId, Nullable<int> teacherUserId, Nullable<int> adminId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var teacherUserIdParameter = teacherUserId.HasValue ?
                new ObjectParameter("TeacherUserId", teacherUserId) :
                new ObjectParameter("TeacherUserId", typeof(int));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AssignCurator", groupIdParameter, teacherUserIdParameter, adminIdParameter);
        }
    
        public virtual ObjectResult<sp_AttendanceReport_Result> sp_AttendanceReport(Nullable<int> groupId, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AttendanceReport_Result>("sp_AttendanceReport", groupIdParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_CreateAnnouncement(string title, string body, Nullable<int> authorId, string targetAudience, Nullable<int> targetGroupId, Nullable<int> targetUserId, Nullable<System.DateTime> expiresAt)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var authorIdParameter = authorId.HasValue ?
                new ObjectParameter("AuthorId", authorId) :
                new ObjectParameter("AuthorId", typeof(int));
    
            var targetAudienceParameter = targetAudience != null ?
                new ObjectParameter("TargetAudience", targetAudience) :
                new ObjectParameter("TargetAudience", typeof(string));
    
            var targetGroupIdParameter = targetGroupId.HasValue ?
                new ObjectParameter("TargetGroupId", targetGroupId) :
                new ObjectParameter("TargetGroupId", typeof(int));
    
            var targetUserIdParameter = targetUserId.HasValue ?
                new ObjectParameter("TargetUserId", targetUserId) :
                new ObjectParameter("TargetUserId", typeof(int));
    
            var expiresAtParameter = expiresAt.HasValue ?
                new ObjectParameter("ExpiresAt", expiresAt) :
                new ObjectParameter("ExpiresAt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_CreateAnnouncement", titleParameter, bodyParameter, authorIdParameter, targetAudienceParameter, targetGroupIdParameter, targetUserIdParameter, expiresAtParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_DeleteAnnouncement(Nullable<int> announcementId, Nullable<int> deletedById)
        {
            var announcementIdParameter = announcementId.HasValue ?
                new ObjectParameter("AnnouncementId", announcementId) :
                new ObjectParameter("AnnouncementId", typeof(int));
    
            var deletedByIdParameter = deletedById.HasValue ?
                new ObjectParameter("DeletedById", deletedById) :
                new ObjectParameter("DeletedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteAnnouncement", announcementIdParameter, deletedByIdParameter);
        }
    
        public virtual int sp_DeleteAttendanceMark(Nullable<int> attendanceId, Nullable<int> userId)
        {
            var attendanceIdParameter = attendanceId.HasValue ?
                new ObjectParameter("AttendanceId", attendanceId) :
                new ObjectParameter("AttendanceId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteAttendanceMark", attendanceIdParameter, userIdParameter);
        }
    
        public virtual int sp_DeleteScheduleItem(Nullable<int> scheduleId, Nullable<int> deletedById)
        {
            var scheduleIdParameter = scheduleId.HasValue ?
                new ObjectParameter("ScheduleId", scheduleId) :
                new ObjectParameter("ScheduleId", typeof(int));
    
            var deletedByIdParameter = deletedById.HasValue ?
                new ObjectParameter("DeletedById", deletedById) :
                new ObjectParameter("DeletedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteScheduleItem", scheduleIdParameter, deletedByIdParameter);
        }
    
        public virtual int sp_DeleteStudentPhoto(Nullable<int> studentId, Nullable<int> deletedById)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var deletedByIdParameter = deletedById.HasValue ?
                new ObjectParameter("DeletedById", deletedById) :
                new ObjectParameter("DeletedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteStudentPhoto", studentIdParameter, deletedByIdParameter);
        }
    
        public virtual ObjectResult<sp_DownloadAttachment_Result> sp_DownloadAttachment(Nullable<int> attachmentId)
        {
            var attachmentIdParameter = attachmentId.HasValue ?
                new ObjectParameter("AttachmentId", attachmentId) :
                new ObjectParameter("AttachmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DownloadAttachment_Result>("sp_DownloadAttachment", attachmentIdParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_GetAcademicYears_Result> sp_GetAcademicYears()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAcademicYears_Result>("sp_GetAcademicYears");
        }
    
        public virtual ObjectResult<sp_GetAdminAlerts_Result> sp_GetAdminAlerts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAdminAlerts_Result>("sp_GetAdminAlerts");
        }
    
        public virtual ObjectResult<sp_GetAdminAttendanceToday_Result> sp_GetAdminAttendanceToday()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAdminAttendanceToday_Result>("sp_GetAdminAttendanceToday");
        }
    
        public virtual ObjectResult<sp_GetAdminGroupStats_Result> sp_GetAdminGroupStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAdminGroupStats_Result>("sp_GetAdminGroupStats");
        }
    
        public virtual ObjectResult<sp_GetAllActiveUsers_Result> sp_GetAllActiveUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllActiveUsers_Result>("sp_GetAllActiveUsers");
        }
    
        public virtual ObjectResult<sp_GetAllGroups_Result> sp_GetAllGroups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllGroups_Result>("sp_GetAllGroups");
        }
    
        public virtual ObjectResult<sp_GetAllTeachers_Result> sp_GetAllTeachers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllTeachers_Result>("sp_GetAllTeachers");
        }
    
        public virtual ObjectResult<sp_GetAllUsers_Result> sp_GetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllUsers_Result>("sp_GetAllUsers");
        }
    
        public virtual ObjectResult<sp_GetAnnouncementAttachmentsMeta_Result> sp_GetAnnouncementAttachmentsMeta(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAnnouncementAttachmentsMeta_Result>("sp_GetAnnouncementAttachmentsMeta", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetAnnouncements_Result> sp_GetAnnouncements(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAnnouncements_Result>("sp_GetAnnouncements", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetAttendanceReport_Result> sp_GetAttendanceReport(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAttendanceReport_Result>("sp_GetAttendanceReport", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetAuditDetail_Result> sp_GetAuditDetail(Nullable<int> logId)
        {
            var logIdParameter = logId.HasValue ?
                new ObjectParameter("LogId", logId) :
                new ObjectParameter("LogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAuditDetail_Result>("sp_GetAuditDetail", logIdParameter);
        }
    
        public virtual ObjectResult<sp_GetAuditLog_Result> sp_GetAuditLog(Nullable<int> limit)
        {
            var limitParameter = limit.HasValue ?
                new ObjectParameter("Limit", limit) :
                new ObjectParameter("Limit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAuditLog_Result>("sp_GetAuditLog", limitParameter);
        }
    
        public virtual ObjectResult<sp_GetCurators_Result> sp_GetCurators()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCurators_Result>("sp_GetCurators");
        }
    
        public virtual ObjectResult<sp_GetCuratorSchedule_Result> sp_GetCuratorSchedule(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCuratorSchedule_Result>("sp_GetCuratorSchedule", userIdParameter);
        }
    
        public virtual ObjectResult<sp_GetCurrentYear_Result> sp_GetCurrentYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCurrentYear_Result>("sp_GetCurrentYear");
        }
    
        public virtual ObjectResult<sp_GetDashboard_Result> sp_GetDashboard(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDashboard_Result>("sp_GetDashboard", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetDashboardEvents_Result> sp_GetDashboardEvents(Nullable<int> userId, string roleName, Nullable<int> limit)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("Limit", limit) :
                new ObjectParameter("Limit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDashboardEvents_Result>("sp_GetDashboardEvents", userIdParameter, roleNameParameter, limitParameter);
        }
    
        public virtual ObjectResult<sp_GetDormitories_Result> sp_GetDormitories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDormitories_Result>("sp_GetDormitories");
        }
    
        public virtual ObjectResult<sp_GetGroupAttendance_Result> sp_GetGroupAttendance(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGroupAttendance_Result>("sp_GetGroupAttendance", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetGroupDetails_Result> sp_GetGroupDetails(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGroupDetails_Result>("sp_GetGroupDetails", groupIdParameter);
        }
    
        public virtual ObjectResult<sp_GetGroupGrades_Result> sp_GetGroupGrades(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGroupGrades_Result>("sp_GetGroupGrades", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetGroupSchedule_Result> sp_GetGroupSchedule(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGroupSchedule_Result>("sp_GetGroupSchedule", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetGroupsForUser_Result> sp_GetGroupsForUser(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGroupsForUser_Result>("sp_GetGroupsForUser", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetGroupSubjects_Result> sp_GetGroupSubjects(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGroupSubjects_Result>("sp_GetGroupSubjects", groupIdParameter);
        }
    
        public virtual ObjectResult<sp_GetJournalData_Result> sp_GetJournalData(Nullable<int> groupId, Nullable<int> subjectId, Nullable<int> year, Nullable<int> month)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetJournalData_Result>("sp_GetJournalData", groupIdParameter, subjectIdParameter, yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<sp_GetJournalMonthly_Result> sp_GetJournalMonthly(Nullable<int> groupId, Nullable<int> subjectId, Nullable<int> year, Nullable<int> month)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetJournalMonthly_Result>("sp_GetJournalMonthly", groupIdParameter, subjectIdParameter, yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<sp_GetLessonNotes_Result> sp_GetLessonNotes(Nullable<int> groupId, Nullable<int> subjectId, Nullable<int> year, Nullable<int> month)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLessonNotes_Result>("sp_GetLessonNotes", groupIdParameter, subjectIdParameter, yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<sp_GetLessonsForMarking_Result> sp_GetLessonsForMarking(Nullable<int> userId, string roleName, Nullable<System.DateTime> date)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLessonsForMarking_Result>("sp_GetLessonsForMarking", userIdParameter, roleNameParameter, dateParameter);
        }
    
        public virtual ObjectResult<sp_GetMonthlyStatement_Result> sp_GetMonthlyStatement(Nullable<int> groupId, Nullable<int> year, Nullable<int> month)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMonthlyStatement_Result>("sp_GetMonthlyStatement", groupIdParameter, yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<string> sp_GetNextStudentCode(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetNextStudentCode", groupIdParameter);
        }
    
        public virtual ObjectResult<sp_GetRecentAudit_Result> sp_GetRecentAudit(Nullable<int> limit)
        {
            var limitParameter = limit.HasValue ?
                new ObjectParameter("Limit", limit) :
                new ObjectParameter("Limit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRecentAudit_Result>("sp_GetRecentAudit", limitParameter);
        }
    
        public virtual ObjectResult<sp_GetScheduleAdmin_Result> sp_GetScheduleAdmin(Nullable<int> groupId, Nullable<int> teacherId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var teacherIdParameter = teacherId.HasValue ?
                new ObjectParameter("TeacherId", teacherId) :
                new ObjectParameter("TeacherId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetScheduleAdmin_Result>("sp_GetScheduleAdmin", groupIdParameter, teacherIdParameter);
        }
    
        public virtual ObjectResult<sp_GetScheduleForDay_Result> sp_GetScheduleForDay(Nullable<int> groupId, Nullable<byte> dayOfWeek, string weekType)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var dayOfWeekParameter = dayOfWeek.HasValue ?
                new ObjectParameter("DayOfWeek", dayOfWeek) :
                new ObjectParameter("DayOfWeek", typeof(byte));
    
            var weekTypeParameter = weekType != null ?
                new ObjectParameter("WeekType", weekType) :
                new ObjectParameter("WeekType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetScheduleForDay_Result>("sp_GetScheduleForDay", groupIdParameter, dayOfWeekParameter, weekTypeParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentAchievements_Result> sp_GetStudentAchievements(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentAchievements_Result>("sp_GetStudentAchievements", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentAttendance_Result> sp_GetStudentAttendance(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentAttendance_Result>("sp_GetStudentAttendance", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentDetails_Result> sp_GetStudentDetails(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentDetails_Result>("sp_GetStudentDetails", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentDocuments_Result> sp_GetStudentDocuments(Nullable<int> studentId, Nullable<int> viewerUserId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var viewerUserIdParameter = viewerUserId.HasValue ?
                new ObjectParameter("ViewerUserId", viewerUserId) :
                new ObjectParameter("ViewerUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentDocuments_Result>("sp_GetStudentDocuments", studentIdParameter, viewerUserIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentGrades_Result> sp_GetStudentGrades(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentGrades_Result>("sp_GetStudentGrades", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentParents_Result> sp_GetStudentParents(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentParents_Result>("sp_GetStudentParents", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentPhoto_Result> sp_GetStudentPhoto(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentPhoto_Result>("sp_GetStudentPhoto", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentsByRole_Result> sp_GetStudentsByRole(Nullable<int> userId, string roleName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentsByRole_Result>("sp_GetStudentsByRole", userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentsForMarking_Result> sp_GetStudentsForMarking(Nullable<int> scheduleId, Nullable<System.DateTime> lessonDate)
        {
            var scheduleIdParameter = scheduleId.HasValue ?
                new ObjectParameter("ScheduleId", scheduleId) :
                new ObjectParameter("ScheduleId", typeof(int));
    
            var lessonDateParameter = lessonDate.HasValue ?
                new ObjectParameter("LessonDate", lessonDate) :
                new ObjectParameter("LessonDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentsForMarking_Result>("sp_GetStudentsForMarking", scheduleIdParameter, lessonDateParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentSocial_Result> sp_GetStudentSocial(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentSocial_Result>("sp_GetStudentSocial", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetSubjectsAdmin_Result> sp_GetSubjectsAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSubjectsAdmin_Result>("sp_GetSubjectsAdmin");
        }
    
        public virtual ObjectResult<sp_GetSubjectsAll_Result> sp_GetSubjectsAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSubjectsAll_Result>("sp_GetSubjectsAll");
        }
    
        public virtual ObjectResult<sp_GetSubjectsForGrades_Result> sp_GetSubjectsForGrades(Nullable<int> groupId, Nullable<int> userId, string roleName)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSubjectsForGrades_Result>("sp_GetSubjectsForGrades", groupIdParameter, userIdParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_GetTeachers_Result> sp_GetTeachers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTeachers_Result>("sp_GetTeachers");
        }
    
        public virtual ObjectResult<sp_GetTeachersAll_Result> sp_GetTeachersAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTeachersAll_Result>("sp_GetTeachersAll");
        }
    
        public virtual ObjectResult<sp_GetTeacherSchedule_Result> sp_GetTeacherSchedule(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTeacherSchedule_Result>("sp_GetTeacherSchedule", userIdParameter);
        }
    
        public virtual ObjectResult<sp_GetTeachersForCurator_Result> sp_GetTeachersForCurator(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTeachersForCurator_Result>("sp_GetTeachersForCurator", groupIdParameter);
        }
    
        public virtual ObjectResult<sp_GetTodaySchedule_Result> sp_GetTodaySchedule(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTodaySchedule_Result>("sp_GetTodaySchedule", groupIdParameter);
        }
    
        public virtual ObjectResult<sp_GetUserDetails_Result> sp_GetUserDetails(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserDetails_Result>("sp_GetUserDetails", userIdParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_ImportScheduleItem(string groupName, Nullable<byte> dayOfWeek, Nullable<byte> lessonNumber, string subjectName, string classroom, string weekType, string teacherName)
        {
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            var dayOfWeekParameter = dayOfWeek.HasValue ?
                new ObjectParameter("DayOfWeek", dayOfWeek) :
                new ObjectParameter("DayOfWeek", typeof(byte));
    
            var lessonNumberParameter = lessonNumber.HasValue ?
                new ObjectParameter("LessonNumber", lessonNumber) :
                new ObjectParameter("LessonNumber", typeof(byte));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var classroomParameter = classroom != null ?
                new ObjectParameter("Classroom", classroom) :
                new ObjectParameter("Classroom", typeof(string));
    
            var weekTypeParameter = weekType != null ?
                new ObjectParameter("WeekType", weekType) :
                new ObjectParameter("WeekType", typeof(string));
    
            var teacherNameParameter = teacherName != null ?
                new ObjectParameter("TeacherName", teacherName) :
                new ObjectParameter("TeacherName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ImportScheduleItem", groupNameParameter, dayOfWeekParameter, lessonNumberParameter, subjectNameParameter, classroomParameter, weekTypeParameter, teacherNameParameter);
        }
    
        public virtual ObjectResult<sp_Login_Result> sp_Login(string login, string passwordHash, string iPAddress)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Login_Result>("sp_Login", loginParameter, passwordHashParameter, iPAddressParameter);
        }
    
        public virtual int sp_LogView(Nullable<int> viewerUserId, string targetTable, Nullable<int> recordId, string viewTarget, string iPAddress)
        {
            var viewerUserIdParameter = viewerUserId.HasValue ?
                new ObjectParameter("ViewerUserId", viewerUserId) :
                new ObjectParameter("ViewerUserId", typeof(int));
    
            var targetTableParameter = targetTable != null ?
                new ObjectParameter("TargetTable", targetTable) :
                new ObjectParameter("TargetTable", typeof(string));
    
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("RecordId", recordId) :
                new ObjectParameter("RecordId", typeof(int));
    
            var viewTargetParameter = viewTarget != null ?
                new ObjectParameter("ViewTarget", viewTarget) :
                new ObjectParameter("ViewTarget", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LogView", viewerUserIdParameter, targetTableParameter, recordIdParameter, viewTargetParameter, iPAddressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MarkAttendance(Nullable<int> studentId, Nullable<int> scheduleId, Nullable<System.DateTime> lessonDate, string status, string reason, Nullable<int> markedById)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var scheduleIdParameter = scheduleId.HasValue ?
                new ObjectParameter("ScheduleId", scheduleId) :
                new ObjectParameter("ScheduleId", typeof(int));
    
            var lessonDateParameter = lessonDate.HasValue ?
                new ObjectParameter("LessonDate", lessonDate) :
                new ObjectParameter("LessonDate", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            var markedByIdParameter = markedById.HasValue ?
                new ObjectParameter("MarkedById", markedById) :
                new ObjectParameter("MarkedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MarkAttendance", studentIdParameter, scheduleIdParameter, lessonDateParameter, statusParameter, reasonParameter, markedByIdParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_Restore(string tableName, Nullable<int> recordId, Nullable<int> restoredById)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("RecordId", recordId) :
                new ObjectParameter("RecordId", typeof(int));
    
            var restoredByIdParameter = restoredById.HasValue ?
                new ObjectParameter("RestoredById", restoredById) :
                new ObjectParameter("RestoredById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Restore", tableNameParameter, recordIdParameter, restoredByIdParameter);
        }
    
        public virtual int sp_SaveAttendanceMark(Nullable<int> markedById, Nullable<int> studentId, Nullable<int> scheduleId, Nullable<System.DateTime> lessonDate, string status, string reason)
        {
            var markedByIdParameter = markedById.HasValue ?
                new ObjectParameter("MarkedById", markedById) :
                new ObjectParameter("MarkedById", typeof(int));
    
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var scheduleIdParameter = scheduleId.HasValue ?
                new ObjectParameter("ScheduleId", scheduleId) :
                new ObjectParameter("ScheduleId", typeof(int));
    
            var lessonDateParameter = lessonDate.HasValue ?
                new ObjectParameter("LessonDate", lessonDate) :
                new ObjectParameter("LessonDate", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveAttendanceMark", markedByIdParameter, studentIdParameter, scheduleIdParameter, lessonDateParameter, statusParameter, reasonParameter);
        }
    
        public virtual int sp_SaveLessonNote(Nullable<int> groupId, Nullable<int> subjectId, Nullable<System.DateTime> lessonDate, string noteText, Nullable<int> userId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var lessonDateParameter = lessonDate.HasValue ?
                new ObjectParameter("LessonDate", lessonDate) :
                new ObjectParameter("LessonDate", typeof(System.DateTime));
    
            var noteTextParameter = noteText != null ?
                new ObjectParameter("NoteText", noteText) :
                new ObjectParameter("NoteText", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveLessonNote", groupIdParameter, subjectIdParameter, lessonDateParameter, noteTextParameter, userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_SaveScheduleItem(Nullable<int> scheduleId, Nullable<int> groupId, Nullable<byte> dayOfWeek, Nullable<byte> lessonNumber, Nullable<int> subjectId, string classroom, string weekType)
        {
            var scheduleIdParameter = scheduleId.HasValue ?
                new ObjectParameter("ScheduleId", scheduleId) :
                new ObjectParameter("ScheduleId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var dayOfWeekParameter = dayOfWeek.HasValue ?
                new ObjectParameter("DayOfWeek", dayOfWeek) :
                new ObjectParameter("DayOfWeek", typeof(byte));
    
            var lessonNumberParameter = lessonNumber.HasValue ?
                new ObjectParameter("LessonNumber", lessonNumber) :
                new ObjectParameter("LessonNumber", typeof(byte));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var classroomParameter = classroom != null ?
                new ObjectParameter("Classroom", classroom) :
                new ObjectParameter("Classroom", typeof(string));
    
            var weekTypeParameter = weekType != null ?
                new ObjectParameter("WeekType", weekType) :
                new ObjectParameter("WeekType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_SaveScheduleItem", scheduleIdParameter, groupIdParameter, dayOfWeekParameter, lessonNumberParameter, subjectIdParameter, classroomParameter, weekTypeParameter);
        }
    
        public virtual int sp_SetGrade(Nullable<int> studentId, Nullable<int> subjectId, Nullable<int> addedById, Nullable<System.DateTime> gradeDate, Nullable<byte> gradeValue)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var addedByIdParameter = addedById.HasValue ?
                new ObjectParameter("AddedById", addedById) :
                new ObjectParameter("AddedById", typeof(int));
    
            var gradeDateParameter = gradeDate.HasValue ?
                new ObjectParameter("GradeDate", gradeDate) :
                new ObjectParameter("GradeDate", typeof(System.DateTime));
    
            var gradeValueParameter = gradeValue.HasValue ?
                new ObjectParameter("GradeValue", gradeValue) :
                new ObjectParameter("GradeValue", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SetGrade", studentIdParameter, subjectIdParameter, addedByIdParameter, gradeDateParameter, gradeValueParameter);
        }
    
        public virtual int sp_SetMonthlyGrade(Nullable<int> studentId, Nullable<int> subjectId, Nullable<int> year, Nullable<int> month, Nullable<byte> finalGrade, Nullable<int> updatedById)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var finalGradeParameter = finalGrade.HasValue ?
                new ObjectParameter("FinalGrade", finalGrade) :
                new ObjectParameter("FinalGrade", typeof(byte));
    
            var updatedByIdParameter = updatedById.HasValue ?
                new ObjectParameter("UpdatedById", updatedById) :
                new ObjectParameter("UpdatedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SetMonthlyGrade", studentIdParameter, subjectIdParameter, yearParameter, monthParameter, finalGradeParameter, updatedByIdParameter);
        }
    
        public virtual int sp_SoftDelete(string tableName, Nullable<int> recordId, Nullable<int> deletedById)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("RecordId", recordId) :
                new ObjectParameter("RecordId", typeof(int));
    
            var deletedByIdParameter = deletedById.HasValue ?
                new ObjectParameter("DeletedById", deletedById) :
                new ObjectParameter("DeletedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SoftDelete", tableNameParameter, recordIdParameter, deletedByIdParameter);
        }
    
        public virtual int sp_ToggleAnnPin(Nullable<int> announcementId, Nullable<int> userId)
        {
            var announcementIdParameter = announcementId.HasValue ?
                new ObjectParameter("AnnouncementId", announcementId) :
                new ObjectParameter("AnnouncementId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ToggleAnnPin", announcementIdParameter, userIdParameter);
        }
    
        public virtual int sp_ToggleUserActive(Nullable<int> userId, Nullable<int> adminId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ToggleUserActive", userIdParameter, adminIdParameter);
        }
    
        public virtual int sp_UpdateAcademicYear(Nullable<int> yearId, string title, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> isCurrent, Nullable<int> adminId)
        {
            var yearIdParameter = yearId.HasValue ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var isCurrentParameter = isCurrent.HasValue ?
                new ObjectParameter("IsCurrent", isCurrent) :
                new ObjectParameter("IsCurrent", typeof(bool));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateAcademicYear", yearIdParameter, titleParameter, startDateParameter, endDateParameter, isCurrentParameter, adminIdParameter);
        }
    
        public virtual int sp_UpdateDormitory(Nullable<int> dormitoryId, string name, string address, string commandantName, string phone, Nullable<int> totalRooms, Nullable<int> adminId)
        {
            var dormitoryIdParameter = dormitoryId.HasValue ?
                new ObjectParameter("DormitoryId", dormitoryId) :
                new ObjectParameter("DormitoryId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var commandantNameParameter = commandantName != null ?
                new ObjectParameter("CommandantName", commandantName) :
                new ObjectParameter("CommandantName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var totalRoomsParameter = totalRooms.HasValue ?
                new ObjectParameter("TotalRooms", totalRooms) :
                new ObjectParameter("TotalRooms", typeof(int));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateDormitory", dormitoryIdParameter, nameParameter, addressParameter, commandantNameParameter, phoneParameter, totalRoomsParameter, adminIdParameter);
        }
    
        public virtual int sp_UpdateGroup(Nullable<int> groupId, Nullable<int> curatorId, string groupName, string specialty, string specialtyCode, Nullable<byte> course, Nullable<byte> semester, string eduForm, string eduBasis, Nullable<int> adminId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var curatorIdParameter = curatorId.HasValue ?
                new ObjectParameter("CuratorId", curatorId) :
                new ObjectParameter("CuratorId", typeof(int));
    
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            var specialtyParameter = specialty != null ?
                new ObjectParameter("Specialty", specialty) :
                new ObjectParameter("Specialty", typeof(string));
    
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("SpecialtyCode", specialtyCode) :
                new ObjectParameter("SpecialtyCode", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(byte));
    
            var semesterParameter = semester.HasValue ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(byte));
    
            var eduFormParameter = eduForm != null ?
                new ObjectParameter("EduForm", eduForm) :
                new ObjectParameter("EduForm", typeof(string));
    
            var eduBasisParameter = eduBasis != null ?
                new ObjectParameter("EduBasis", eduBasis) :
                new ObjectParameter("EduBasis", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateGroup", groupIdParameter, curatorIdParameter, groupNameParameter, specialtyParameter, specialtyCodeParameter, courseParameter, semesterParameter, eduFormParameter, eduBasisParameter, adminIdParameter);
        }
    
        public virtual int sp_UpdateStudent(Nullable<int> studentId, string lastName, string firstName, string middleName, string phone, string email, string address, Nullable<int> groupId, Nullable<System.DateTime> birthDate, string gender, string studyBasis, string studentCode, Nullable<bool> isHeadman, Nullable<int> updatedById)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var birthDateParameter = birthDate.HasValue ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var studyBasisParameter = studyBasis != null ?
                new ObjectParameter("StudyBasis", studyBasis) :
                new ObjectParameter("StudyBasis", typeof(string));
    
            var studentCodeParameter = studentCode != null ?
                new ObjectParameter("StudentCode", studentCode) :
                new ObjectParameter("StudentCode", typeof(string));
    
            var isHeadmanParameter = isHeadman.HasValue ?
                new ObjectParameter("IsHeadman", isHeadman) :
                new ObjectParameter("IsHeadman", typeof(bool));
    
            var updatedByIdParameter = updatedById.HasValue ?
                new ObjectParameter("UpdatedById", updatedById) :
                new ObjectParameter("UpdatedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateStudent", studentIdParameter, lastNameParameter, firstNameParameter, middleNameParameter, phoneParameter, emailParameter, addressParameter, groupIdParameter, birthDateParameter, genderParameter, studyBasisParameter, studentCodeParameter, isHeadmanParameter, updatedByIdParameter);
        }
    
        public virtual int sp_UpdateSubject(Nullable<int> subjectId, Nullable<int> groupId, Nullable<int> teacherId, string subjectName, Nullable<int> hoursTotal, Nullable<int> hoursLecture, Nullable<int> hoursPractice, Nullable<int> hoursLab, Nullable<int> hoursSelfStudy, string semester, string controlType, Nullable<int> adminId)
        {
            var subjectIdParameter = subjectId.HasValue ?
                new ObjectParameter("SubjectId", subjectId) :
                new ObjectParameter("SubjectId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var teacherIdParameter = teacherId.HasValue ?
                new ObjectParameter("TeacherId", teacherId) :
                new ObjectParameter("TeacherId", typeof(int));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var hoursTotalParameter = hoursTotal.HasValue ?
                new ObjectParameter("HoursTotal", hoursTotal) :
                new ObjectParameter("HoursTotal", typeof(int));
    
            var hoursLectureParameter = hoursLecture.HasValue ?
                new ObjectParameter("HoursLecture", hoursLecture) :
                new ObjectParameter("HoursLecture", typeof(int));
    
            var hoursPracticeParameter = hoursPractice.HasValue ?
                new ObjectParameter("HoursPractice", hoursPractice) :
                new ObjectParameter("HoursPractice", typeof(int));
    
            var hoursLabParameter = hoursLab.HasValue ?
                new ObjectParameter("HoursLab", hoursLab) :
                new ObjectParameter("HoursLab", typeof(int));
    
            var hoursSelfStudyParameter = hoursSelfStudy.HasValue ?
                new ObjectParameter("HoursSelfStudy", hoursSelfStudy) :
                new ObjectParameter("HoursSelfStudy", typeof(int));
    
            var semesterParameter = semester != null ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(string));
    
            var controlTypeParameter = controlType != null ?
                new ObjectParameter("ControlType", controlType) :
                new ObjectParameter("ControlType", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateSubject", subjectIdParameter, groupIdParameter, teacherIdParameter, subjectNameParameter, hoursTotalParameter, hoursLectureParameter, hoursPracticeParameter, hoursLabParameter, hoursSelfStudyParameter, semesterParameter, controlTypeParameter, adminIdParameter);
        }
    
        public virtual int sp_UpdateTeacher(Nullable<int> teacherId, string lastName, string firstName, string middleName, Nullable<bool> isActive, Nullable<int> adminId)
        {
            var teacherIdParameter = teacherId.HasValue ?
                new ObjectParameter("TeacherId", teacherId) :
                new ObjectParameter("TeacherId", typeof(int));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateTeacher", teacherIdParameter, lastNameParameter, firstNameParameter, middleNameParameter, isActiveParameter, adminIdParameter);
        }
    
        public virtual int sp_UpdateUser(Nullable<int> userId, string login, string roleName, string lastName, string firstName, string middleName, string phone, string email, Nullable<int> adminId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateUser", userIdParameter, loginParameter, roleNameParameter, lastNameParameter, firstNameParameter, middleNameParameter, phoneParameter, emailParameter, adminIdParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_UploadStudentPhoto(Nullable<int> studentId, byte[] photoData, string mimeType, Nullable<int> uploadedById)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var photoDataParameter = photoData != null ?
                new ObjectParameter("PhotoData", photoData) :
                new ObjectParameter("PhotoData", typeof(byte[]));
    
            var mimeTypeParameter = mimeType != null ?
                new ObjectParameter("MimeType", mimeType) :
                new ObjectParameter("MimeType", typeof(string));
    
            var uploadedByIdParameter = uploadedById.HasValue ?
                new ObjectParameter("UploadedById", uploadedById) :
                new ObjectParameter("UploadedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UploadStudentPhoto", studentIdParameter, photoDataParameter, mimeTypeParameter, uploadedByIdParameter);
        }
    }
}
