//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyGrades
    {
        public int MonthlyGradeId { get; set; }
        public int StudentId { get; set; }
        public int SubjectId { get; set; }
        public short GradeYear { get; set; }
        public byte GradeMonth { get; set; }
        public Nullable<decimal> CalculatedAvg { get; set; }
        public Nullable<byte> FinalGrade { get; set; }
        public bool IsOverridden { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
