//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        public int ParentId { get; set; }
        public int StudentId { get; set; }
        public string Relation { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone { get; set; }
        public string WorkPhone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Workplace { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string Education { get; set; }
        public bool IsMainContact { get; set; }
        public bool IsDeceased { get; set; }
        public bool HasParentalRights { get; set; }
        public string AdditionalInfo { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Students Students { get; set; }
    }
}
