//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int ScheduleId { get; set; }
        public int SubjectId { get; set; }
        public int GroupId { get; set; }
        public byte DayOfWeek { get; set; }
        public byte LessonNumber { get; set; }
        public string Classroom { get; set; }
        public string WeekType { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
