//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public Students()
        {
            this.Achievements = new HashSet<Achievements>();
            this.Assignments = new HashSet<Assignments>();
            this.Attendance = new HashSet<Attendance>();
            this.Grades = new HashSet<Grades>();
            this.MonthlyGrades = new HashSet<MonthlyGrades>();
            this.Parents = new HashSet<Parents>();
            this.StudentSocialInfo = new HashSet<StudentSocialInfo>();
        }
    
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> DormitoryId { get; set; }
        public bool IsHeadman { get; set; }
        public string StudentCode { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string Gender { get; set; }
        public string Citizenship { get; set; }
        public string Nationality { get; set; }
        public string Address { get; set; }
        public string RegisteredAddress { get; set; }
        public string SNILSNumber { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string PassportIssuedBy { get; set; }
        public Nullable<System.DateTime> PassportIssuedDate { get; set; }
        public string PreviousSchool { get; set; }
        public string PreviousSchoolType { get; set; }
        public Nullable<byte> PreviousSchoolGrade { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public string EnrollmentOrderNumber { get; set; }
        public string StudyBasis { get; set; }
        public string RoomNumber { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
        public byte[] PhotoData { get; set; }
        public string PhotoMimeType { get; set; }
    
        public virtual ICollection<Achievements> Achievements { get; set; }
        public virtual ICollection<Assignments> Assignments { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Dormitories Dormitories { get; set; }
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual ICollection<MonthlyGrades> MonthlyGrades { get; set; }
        public virtual ICollection<Parents> Parents { get; set; }
        public virtual ICollection<StudentSocialInfo> StudentSocialInfo { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
