//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSocialInfo
    {
        public int SocialInfoId { get; set; }
        public int StudentId { get; set; }
        public string HealthGroup { get; set; }
        public string ChronicDiseases { get; set; }
        public string Disability { get; set; }
        public string DisabilityGroup { get; set; }
        public string DisabilityCertificate { get; set; }
        public bool IsOrphan { get; set; }
        public bool IsHalfOrphan { get; set; }
        public bool IsFromLargeFamily { get; set; }
        public bool IsLowIncome { get; set; }
        public bool IsSociallyVulnerable { get; set; }
        public bool IsOnGuardianship { get; set; }
        public string SocialBenefits { get; set; }
        public string PsychologicalFeatures { get; set; }
        public string HousingCondition { get; set; }
        public string FamilyStructure { get; set; }
        public string FamilyType { get; set; }
        public string AdditionalNotes { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
