//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.Grades = new HashSet<Grades>();
            this.LessonNotes = new HashSet<LessonNotes>();
            this.MonthlyGrades = new HashSet<MonthlyGrades>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int SubjectId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string SubjectName { get; set; }
        public string SubjectCode { get; set; }
        public int HoursTotal { get; set; }
        public int HoursLecture { get; set; }
        public int HoursPractice { get; set; }
        public int HoursLab { get; set; }
        public int HoursSelfStudy { get; set; }
        public string Semester { get; set; }
        public string ControlType { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual ICollection<LessonNotes> LessonNotes { get; set; }
        public virtual ICollection<MonthlyGrades> MonthlyGrades { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual Users Users { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
