//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AcademicYears = new HashSet<AcademicYears>();
            this.Achievements = new HashSet<Achievements>();
            this.Achievements1 = new HashSet<Achievements>();
            this.AnnouncementAttachments = new HashSet<AnnouncementAttachments>();
            this.AnnouncementPins = new HashSet<AnnouncementPins>();
            this.AnnouncementReads = new HashSet<AnnouncementReads>();
            this.Announcements = new HashSet<Announcements>();
            this.Announcements1 = new HashSet<Announcements>();
            this.Announcements2 = new HashSet<Announcements>();
            this.Announcements3 = new HashSet<Announcements>();
            this.Assignments = new HashSet<Assignments>();
            this.Assignments1 = new HashSet<Assignments>();
            this.Attendance = new HashSet<Attendance>();
            this.Attendance1 = new HashSet<Attendance>();
            this.AuditLog = new HashSet<AuditLog>();
            this.CuratorProfiles = new HashSet<CuratorProfiles>();
            this.CuratorProfiles1 = new HashSet<CuratorProfiles>();
            this.Documents = new HashSet<Documents>();
            this.Documents1 = new HashSet<Documents>();
            this.Dormitories = new HashSet<Dormitories>();
            this.EventProtocols = new HashSet<EventProtocols>();
            this.Events = new HashSet<Events>();
            this.Events1 = new HashSet<Events>();
            this.GradeHistory = new HashSet<GradeHistory>();
            this.Grades = new HashSet<Grades>();
            this.Grades1 = new HashSet<Grades>();
            this.Groups = new HashSet<Groups>();
            this.Groups1 = new HashSet<Groups>();
            this.LessonNotes = new HashSet<LessonNotes>();
            this.MonthlyGrades = new HashSet<MonthlyGrades>();
            this.Parents = new HashSet<Parents>();
            this.Schedule = new HashSet<Schedule>();
            this.Students = new HashSet<Students>();
            this.Students1 = new HashSet<Students>();
            this.Subjects = new HashSet<Subjects>();
            this.Teachers = new HashSet<Teachers>();
            this.Teachers1 = new HashSet<Teachers>();
            this.Users1 = new HashSet<Users>();
        }
    
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedById { get; set; }
    
        public virtual ICollection<AcademicYears> AcademicYears { get; set; }
        public virtual ICollection<Achievements> Achievements { get; set; }
        public virtual ICollection<Achievements> Achievements1 { get; set; }
        public virtual ICollection<AnnouncementAttachments> AnnouncementAttachments { get; set; }
        public virtual ICollection<AnnouncementPins> AnnouncementPins { get; set; }
        public virtual ICollection<AnnouncementReads> AnnouncementReads { get; set; }
        public virtual ICollection<Announcements> Announcements { get; set; }
        public virtual ICollection<Announcements> Announcements1 { get; set; }
        public virtual ICollection<Announcements> Announcements2 { get; set; }
        public virtual ICollection<Announcements> Announcements3 { get; set; }
        public virtual ICollection<Assignments> Assignments { get; set; }
        public virtual ICollection<Assignments> Assignments1 { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<Attendance> Attendance1 { get; set; }
        public virtual ICollection<AuditLog> AuditLog { get; set; }
        public virtual ICollection<CuratorProfiles> CuratorProfiles { get; set; }
        public virtual ICollection<CuratorProfiles> CuratorProfiles1 { get; set; }
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ICollection<Documents> Documents1 { get; set; }
        public virtual ICollection<Dormitories> Dormitories { get; set; }
        public virtual ICollection<EventProtocols> EventProtocols { get; set; }
        public virtual ICollection<Events> Events { get; set; }
        public virtual ICollection<Events> Events1 { get; set; }
        public virtual ICollection<GradeHistory> GradeHistory { get; set; }
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual ICollection<Grades> Grades1 { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual ICollection<Groups> Groups1 { get; set; }
        public virtual ICollection<LessonNotes> LessonNotes { get; set; }
        public virtual ICollection<MonthlyGrades> MonthlyGrades { get; set; }
        public virtual ICollection<Parents> Parents { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<Students> Students { get; set; }
        public virtual ICollection<Students> Students1 { get; set; }
        public virtual ICollection<Subjects> Subjects { get; set; }
        public virtual ICollection<Teachers> Teachers { get; set; }
        public virtual ICollection<Teachers> Teachers1 { get; set; }
        public virtual ICollection<Users> Users1 { get; set; }
        public virtual Users Users2 { get; set; }
    }
}
