//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AttendanceSummary
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> TotalLessons { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<int> Late { get; set; }
        public Nullable<int> Excused { get; set; }
        public Nullable<decimal> AttendancePercent { get; set; }
    }
}
