//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AuditLog
    {
        public int LogId { get; set; }
        public System.DateTime ActionAt { get; set; }
        public string UserFullName { get; set; }
        public string RoleName { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordId { get; set; }
        public string ViewTarget { get; set; }
        public string ReadableAction { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public string IPAddress { get; set; }
    }
}
