//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GradeAverage
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string GroupName { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> GradeCount { get; set; }
        public Nullable<decimal> AverageGrade { get; set; }
        public Nullable<byte> MinGrade { get; set; }
        public Nullable<byte> MaxGrade { get; set; }
    }
}
