//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SocialStudents
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string GroupName { get; set; }
        public string HealthGroup { get; set; }
        public string Disability { get; set; }
        public string DisabilityGroup { get; set; }
        public bool IsOrphan { get; set; }
        public bool IsHalfOrphan { get; set; }
        public bool IsFromLargeFamily { get; set; }
        public bool IsLowIncome { get; set; }
        public bool IsSociallyVulnerable { get; set; }
        public bool IsOnGuardianship { get; set; }
        public string FamilyStructure { get; set; }
        public string HousingCondition { get; set; }
    }
}
