//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeJournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentCard
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string StudentCode { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string GroupName { get; set; }
        public string Specialty { get; set; }
        public byte Course { get; set; }
        public byte Semester { get; set; }
        public bool IsHeadman { get; set; }
        public string StudyBasis { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DormitoryName { get; set; }
        public string RoomNumber { get; set; }
        public string HealthGroup { get; set; }
        public Nullable<bool> IsOrphan { get; set; }
        public Nullable<bool> IsHalfOrphan { get; set; }
        public Nullable<bool> IsFromLargeFamily { get; set; }
        public Nullable<bool> IsLowIncome { get; set; }
        public Nullable<bool> IsSociallyVulnerable { get; set; }
        public string Disability { get; set; }
        public string DisabilityGroup { get; set; }
        public string AcademicYear { get; set; }
    }
}
